runtime: python27
api_version: 1
threadsafe: yes

# [START bounce_service]
# [START mail_service]
inbound_services:
- mail
# [END mail_service]

handlers:
# [START handle_incoming_email]
# owner@.*expense-mailer\.appspotmail\.com
- url: /_ah/mail/debug@.*expense-mailer\.appspotmail\.com
  script: debug_incoming_email.app
- url: /_ah/mail/.+
  script: process_incoming_email.app #owner@.*expense-mailer\.appspotmail\.com
- url: /
  static_files: index.html
  upload: index.html
